apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: web # Название контейнера
    image: iakrevetko/web # Образ из которого создается контейнер
    volumeMounts:
    - name: app
      mountPath: /usr/share/nginx/html
    env:
      - name: NGINX_PORT
        value: "8000"  
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
  - name: app
    emptyDir: {}